---
- debug: var=ansible_python_interpreter

- name: Set ansible_python_interpreter=/usr/bin/python3 for RHEL8
  set_fact:
    ansible_python_interpreter: /usr/bin/python3

- debug: var=ansible_python_interpreter

- name: Get the current timezone (RHEL/CentOS 6)
  shell: cut -d'"' -f2 /etc/sysconfig/clock
  when: ansible_distribution_major_version == "6"
  register: current_tz
  changed_when: false
  tags:
    - timezone

- name: Get the current timezone (RHEL/CentOS 7)
  shell: 'timedatectl | grep -E "Time ?zone" | sed -e "s/.*: \(.*\) (.*/\1/"'
  when: ansible_distribution_major_version == "7"
  register: current_tz
  changed_when: false
  tags:
    - timezone

- name: Set /etc/localtime (RHEL/CentOS 6)
  file:
    src: /usr/share/zoneinfo/{{ timezone }}
    dest: /etc/localtime
    state: link
    force: yes
  # Default is used below to avoid breaking check mode
  when: ansible_distribution_major_version == "6" and current_tz.stdout|default("") != timezone
  tags:
    - timezone

- name: Set the timezone (RHEL/CentOS 7)
  command: timedatectl set-timezone {{ timezone }}
  # Default is used below to avoid breaking check mode
  when: ansible_distribution_major_version == "7" and current_tz.stdout|default("") != timezone
  tags:
    - timezone

# This is temporary to provide reverse compatibility with certain
# tasks that call yum specifically.
# Should be deprecated once we move to ansible v2
- name: Install yum on Fedora 22 and later
  dnf:
    name: yum
    state: present
  when: ansible_distribution == 'Fedora' and ansible_distribution_major_version|int >= 22

# configure Red Hat entitlements with subscription-manager
# skip_entitlements=true on OVH testnodes
- import_tasks: rhel-entitlements.yml
  when:
    ansible_distribution == 'RedHat' and
    beta_distro == false and
    skip_entitlements|default(false)|bool != true
  tags:
    - entitlements

# create and manage epel.repo
- import_tasks: epel.yml
  when:
    ansible_distribution == "CentOS" or
    ansible_distribution == 'RedHat'
  tags:
    - epel
    - repos
